// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4DJbDpf1FO47EHbo1GUsdkv-ZLve1oP4',
    appId: '1:527690241621:web:690a3f23c48ba63b9126dc',
    messagingSenderId: '527690241621',
    projectId: 'idcpns-mobile',
    authDomain: 'idcpns-mobile.firebaseapp.com',
    storageBucket: 'idcpns-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSgFpwKp063PS1dKzJitCC9hKr54QWst8',
    appId: '1:527690241621:android:1af85f82e4dc054b9126dc',
    messagingSenderId: '527690241621',
    projectId: 'idcpns-mobile',
    storageBucket: 'idcpns-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy3fztxBi_I7OyiX3iGLvA-FXcId4yfKY',
    appId: '1:527690241621:ios:5c1580963ece59b79126dc',
    messagingSenderId: '527690241621',
    projectId: 'idcpns-mobile',
    storageBucket: 'idcpns-mobile.firebasestorage.app',
    iosBundleId: 'com.example.idcpnsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy3fztxBi_I7OyiX3iGLvA-FXcId4yfKY',
    appId: '1:527690241621:ios:5c1580963ece59b79126dc',
    messagingSenderId: '527690241621',
    projectId: 'idcpns-mobile',
    storageBucket: 'idcpns-mobile.firebasestorage.app',
    iosBundleId: 'com.example.idcpnsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4DJbDpf1FO47EHbo1GUsdkv-ZLve1oP4',
    appId: '1:527690241621:web:141c2822c9e0f7ae9126dc',
    messagingSenderId: '527690241621',
    projectId: 'idcpns-mobile',
    authDomain: 'idcpns-mobile.firebaseapp.com',
    storageBucket: 'idcpns-mobile.firebasestorage.app',
  );
}
