part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const TRYOUT = _Paths.TRYOUT;
  static const DETAIL_TRYOUT = _Paths.DETAIL_TRYOUT;
  static const TRYOUT_PAYMENT = _Paths.TRYOUT_PAYMENT;
  static const TRYOUT_SAYA = _Paths.TRYOUT_SAYA;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const EMAIL_VERIFICATION = _Paths.EMAIL_VERIFICATION;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const ACCOUNT = _Paths.ACCOUNT;
  static const MY_ACCOUNT = _Paths.MY_ACCOUNT;
  static const FORGET_PASSWORD = _Paths.FORGET_PASSWORD;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const TRANSACTION = _Paths.TRANSACTION;
  static const TRYOUT_CHECKOUT = _Paths.TRYOUT_CHECKOUT;
  static const DETAIL_TRYOUT_SAYA = _Paths.DETAIL_TRYOUT_SAYA;
  static const DETAIL_PENGERJAAN_TRYOUT = _Paths.DETAIL_PENGERJAAN_TRYOUT;
  static const PANDUAN_TRYOUT = _Paths.PANDUAN_TRYOUT;
  static const WISHLIST = _Paths.WISHLIST;
  static const PROGRAM_SAYA = _Paths.PROGRAM_SAYA;
  static const AFFILIATE = _Paths.AFFILIATE;
  static const AFFILIATE_DETAIL = _Paths.AFFILIATE_DETAIL;
  static const COMMISION_DETAIL = _Paths.COMMISION_DETAIL;
  static const SPLASH = _Paths.SPLASH;
  static const REKENING = _Paths.REKENING;
  static const MUTASI_SALDO = _Paths.MUTASI_SALDO;
  static const TARIK_KOMISI = _Paths.TARIK_KOMISI;
  static const BIMBEL = _Paths.BIMBEL;
  static const DETAIL_BIMBEL = _Paths.DETAIL_BIMBEL;
  static const MY_BIMBEL = _Paths.MY_BIMBEL;
  static const DETAIL_MY_BIMBEL = _Paths.DETAIL_MY_BIMBEL;
  static const PRETEST_RESULT = _Paths.PRETEST_RESULT;
  static const DETAIL_EVENT = _Paths.DETAIL_EVENT;
  static const PAYMENT_DETAIL = _Paths.PAYMENT_DETAIL;
  static const PRETEST_RANKING = _Paths.PRETEST_RANKING;
  static const BIMBEL_RECORD = _Paths.BIMBEL_RECORD;
  static const TERM_CONDITONS = _Paths.TERM_CONDITONS;
  static const PRETEST_DETAIL = _Paths.PRETEST_DETAIL;
  static const PAYMENT_CHECKOUT = _Paths.PAYMENT_CHECKOUT;
  static const PRETEST = _Paths.PRETEST;
  static const PRETEST_TOUR = _Paths.PRETEST_TOUR;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const TRYOUT = '/tryout';
  static const DETAIL_TRYOUT = '/detail-tryout';
  static const TRYOUT_PAYMENT = '/tryout-payment';
  static const TRYOUT_SAYA = '/tryout-saya';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const DASHBOARD = '/dashboard';
  static const EMAIL_VERIFICATION = '/email-verification';
  static const CHANGE_PASSWORD = '/change-password';
  static const ACCOUNT = '/account';
  static const MY_ACCOUNT = '/my-account';
  static const FORGET_PASSWORD = '/forget-password';
  static const NOTIFICATION = '/notification';
  static const TRANSACTION = '/transaction';
  static const TRYOUT_CHECKOUT = '/tryout-checkout';
  static const DETAIL_TRYOUT_SAYA = '/detail-tryout-saya';
  static const DETAIL_PENGERJAAN_TRYOUT = '/detail-pengerjaan-tryout';
  static const PANDUAN_TRYOUT = '/panduan-tryout';
  static const WISHLIST = '/wishlist';
  static const PROGRAM_SAYA = '/program-saya';
  static const AFFILIATE = '/affiliate';
  static const AFFILIATE_DETAIL = '/affiliate-detail';
  static const COMMISION_DETAIL = '/commision-detail';
  static const SPLASH = '/splash';
  static const PENGERJAAN_TRYOUT = '/pengerjaan-tryout';
  static const REKENING = '/rekening';
  static const MUTASI_SALDO = '/mutasi-saldo';
  static const TARIK_KOMISI = '/tarik-komisi';
  static const BIMBEL = '/bimbel';
  static const DETAIL_BIMBEL = '/detail-bimbel';
  static const MY_BIMBEL = '/my-bimbel';
  static const DETAIL_MY_BIMBEL = '/detail-my-bimbel';
  static const PRETEST_RESULT = '/pretest-result';
  static const DETAIL_EVENT = '/detail-event';
  static const PAYMENT_DETAIL = '/payment-detail';
  static const PRETEST_RANKING = '/pretest-ranking';
  static const BIMBEL_RECORD = '/bimbel-record';
  static const TERM_CONDITONS = '/term-conditons';
  static const PRETEST_DETAIL = '/pretest-detail';
  static const PAYMENT_CHECKOUT = '/payment-checkout';
  static const PRETEST = '/pretest';
  static const PRETEST_TOUR = '/pretest-tour';
}
